In [ ]:
import pandas as pd
import seaborn as sns

df= sns.load_dataset('tips')

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder_time= LabelEncoder()

encoded_data =encoder_time.fit_transform(df['time'])

In [ ]:
print('classes', encoder_time.classes_)

In [ ]:
encoded_data

In [ ]:
for category, number in zip (encoder_time.classes_, range(len(encoder_time.classes_))):
    print(category ,"---------", number)

In [ ]:
encoder_day= LabelEncoder()

encoded_day_data =encoder_day.fit_transform(df['day'])

In [ ]:
print('classes', encoder_day.classes_)

In [ ]:
for category, number in zip (encoder_day.classes_, range(len(encoder_day.classes_))):
    print(category ,"---------", number)

In [ ]:
encoder_day.inverse_transform([0,1,2,3])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe= OneHotEncoder(sparse_output= False)
ohe.fit_transform(df[['sex','smoker']])

In [ ]:
ohe= OneHotEncoder(sparse_output= False, drop= 'first')
ohe_encoder=ohe.fit_transform(df[['sex','smoker']])
ohe_encoder

In [ ]:
df1=pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())
df1

In [ ]:
pd.concat([df,df1],axis=1)

In [ ]:
from sklearn.preprocessing import  FunctionTransformer
import numpy as np

In [ ]:
log=FunctionTransformer(np.log10)
log.fit_transform(df['tip'])

In [ ]:
log_2=FunctionTransformer(np.log2)
log_2.fit_transform(df['tip'])

In [ ]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

# A right-skewed feature
X = np.array([[-1],[0],[3],[5],[10],[50]])
# Create the transformer
pt = PowerTransformer(method="yeo-johnson")
# Fit and transform
X_transformed = pt.fit_transform(X)
print("Original:")
print(X.ravel())
print("\nTransformed:")
print(np.round(X_transformed.ravel(), 3))
print("\nLearned lambda:")
print(pt.lambdas_)

In [ ]:
# A right-skewed feature
y = np.array([[1],[1],[3],[5],[10],[50]])
# Create the transformer
pt = PowerTransformer(method="box-cox")
# Fit and transform
y_transformed = pt.fit_transform(y)
print("Original:")
print(y.ravel())
print("\nTransformed:")
print(np.round(y_transformed.ravel(), 3))
print("\nLearned lambda:")
print(pt.lambdas_)

In [ ]:
import numpy as np
import pandas as pd

# Creating sample dataset
data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    # Categorical columns with nulls
    "Department": [
        "IT",
        "HR",
        np.nan,
        "Finance",
        "IT",
        "Marketing",
        np.nan,
        "Finance",
        "HR",
        "Marketing",
    ],
    "City": [
        "New York",
        "London",
        "Paris",
        np.nan,
        "London",
        np.nan,
        "Berlin",
        "New York",
        "Paris",
        "Berlin",
    ],
    "Education": [
        "Master",
        "Bachelor",
        "Bachelor",
        "PhD",
        np.nan,
        "Master",
        "Bachelor",
        np.nan,
        "PhD",
        "Master",
    ],
    # Numerical columns with nulls
    "Age": [28, np.nan, 35, 42, 29, np.nan, 38, 45, np.nan, 31],
    "Salary": [
        72000,
        58000,
        np.nan,
        95000,
        68000,
        84000,
        np.nan,
        102000,
        89000,
        71000,
    ],
    "Experience_Years": [
        3.5,
        1.0,
        7.0,
        np.nan,
        4.0,
        8.5,
        9.0,
        np.nan,
        10.0,
        5.0,
    ],
}

df = pd.DataFrame(data)

# Check missing values count per column

df.head()

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer= SimpleImputer(strategy='mean')

imputer.fit_transform(df[['Salary']])

In [ ]:
imputer= SimpleImputer(strategy='mean')

df['new_salary']=imputer.fit_transform(df[['Salary']]).flatten()

In [59]:
imputer= SimpleImputer(strategy='median')

df['new_Experience_Years']=imputer.fit_transform(df[['Experience_Years']]).flatten()

In [60]:
df

,Employee_ID,Department,City,Education,Age,Salary,Experience_Years,new_salary,new_Experience_Years
0,101,IT,New York,Master,28.0,72000.0,3.5,72000.0,3.5
1,102,HR,London,Bachelor,NaN,58000.0,1.0,58000.0,1.0
2,103,NaN,Paris,Bachelor,35.0,NaN,7.0,79875.0,7.0
3,104,Finance,NaN,PhD,42.0,95000.0,NaN,95000.0,6.0
4,105,IT,London,NaN,29.0,68000.0,4.0,68000.0,4.0
5,106,Marketing,NaN,Master,NaN,84000.0,8.5,84000.0,8.5
6,107,NaN,Berlin,Bachelor,38.0,NaN,9.0,79875.0,9.0
7,108,Finance,New York,NaN,45.0,102000.0,NaN,102000.0,6.0
8,109,HR,Paris,PhD,NaN,89000.0,10.0,89000.0,10.0
9,110,Marketing,Berlin,Master,31.0,71000.0,5.0,71000.0,5.0

In [61]:
imputer= SimpleImputer(strategy='most_frequent',)

df['City']=imputer.fit_transform(df[['City']]).flatten()

In [62]:
df

,Employee_ID,Department,City,Education,Age,Salary,Experience_Years,new_salary,new_Experience_Years
0,101,IT,New York,Master,28.0,72000.0,3.5,72000.0,3.5
1,102,HR,London,Bachelor,NaN,58000.0,1.0,58000.0,1.0
2,103,NaN,Paris,Bachelor,35.0,NaN,7.0,79875.0,7.0
3,104,Finance,Berlin,PhD,42.0,95000.0,NaN,95000.0,6.0
4,105,IT,London,NaN,29.0,68000.0,4.0,68000.0,4.0
5,106,Marketing,Berlin,Master,NaN,84000.0,8.5,84000.0,8.5
6,107,NaN,Berlin,Bachelor,38.0,NaN,9.0,79875.0,9.0
7,108,Finance,New York,NaN,45.0,102000.0,NaN,102000.0,6.0
8,109,HR,Paris,PhD,NaN,89000.0,10.0,89000.0,10.0
9,110,Marketing,Berlin,Master,31.0,71000.0,5.0,71000.0,5.0